const list = [
    {
        id : 1,
        title : "FOOD 1",
        chief : "ARUN",
        price : 89,
        amount : 1,
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_bo56oT6B0VX_66zG61SK-8F78zI4XgvzUg&usqp=CAU",
    },
    {
        id :2,
        title : "FOOD 2",
        chief : "GEETHA",
        price : 40,
        amount : 1,
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_bo56oT6B0VX_66zG61SK-8F78zI4XgvzUg&usqp=CAU",
    },
    {
        id : 3,
        title : "FOOD 3",
        chief : "ARUN",
        price : 231,
        amount : 1,
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_bo56oT6B0VX_66zG61SK-8F78zI4XgvzUg&usqp=CAU",
    },
    {
        id : 4,
        title : "FOOD 4",
        chief : "GEETHA",
        price : 200,
        amount : 1,
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_bo56oT6B0VX_66zG61SK-8F78zI4XgvzUg&usqp=CAU",
    },
    {
        id : 5,
        title : "FOOD 5",
        chief : "GEETHA",
        price : 189,
        amount : 1,
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_bo56oT6B0VX_66zG61SK-8F78zI4XgvzUg&usqp=CAU",
    },
    {
        id : 6,
        title : "FOOD 6",
        chief : "ARUN",
        price : 120,
        amount : 1,
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_bo56oT6B0VX_66zG61SK-8F78zI4XgvzUg&usqp=CAU",
    },
    {
        id : 7,
        title : "FOOD 7",
        chief : "ARUN",
        price : 59,
        amount : 1,
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_bo56oT6B0VX_66zG61SK-8F78zI4XgvzUg&usqp=CAU",
    },
    {
        id : 8,
        title : "FOOD 8",
        chief : "GEETHA",
        price : 67,
        amount : 1,
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_bo56oT6B0VX_66zG61SK-8F78zI4XgvzUg&usqp=CAU",
    },
    {
        id : 9,
        title : "FOOD 9",
        chief : "ARUN",
        price : 89,
        amount : 1,
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_bo56oT6B0VX_66zG61SK-8F78zI4XgvzUg&usqp=CAU",
    },
    {
        id : 10,
        title : "FOOD 10",
        chief : "GEETHA",
        price : 100,
        amount : 1,
        img : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_bo56oT6B0VX_66zG61SK-8F78zI4XgvzUg&usqp=CAU",
    },
    
]
export default list;